/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iams_g10;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tasnima Hamid
 */
public class cashmanager extends javax.swing.JFrame {

    /**
     * Creates new form cashmanager
     */
    public cashmanager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addbillbtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        datef = new javax.swing.JFormattedTextField();
        chqf = new javax.swing.JTextField();
        amntf = new javax.swing.JTextField();
        statf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        accptbtn = new javax.swing.JButton();
        dclnbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setText("Cheque No");

        jLabel3.setText("Amount");

        jLabel4.setText("Date Added");

        jLabel5.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Cash Section");

        addbillbtn.setText("Add Bills");
        addbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillbtnActionPerformed(evt);
            }
        });

        viewbtn.setText("View All Records");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cheque no", "Amount", "Date Issued", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        datef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        accptbtn.setText("View Accepted Bills");
        accptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accptbtnActionPerformed(evt);
            }
        });

        dclnbtn.setText("View Declined Bills");
        dclnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dclnbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(addbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chqf)
                            .addComponent(amntf)
                            .addComponent(datef)
                            .addComponent(statf, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewbtn)
                                .addGap(31, 31, 31)
                                .addComponent(accptbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dclnbtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewbtn)
                            .addComponent(accptbtn)
                            .addComponent(dclnbtn))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(chqf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(amntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(datef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(addbillbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillbtnActionPerformed
        // TODO add your handling code here:
        String cheq = chqf.getText();
        String amnt = amntf.getText();
        float amount = Float.parseFloat(amnt);
        String date = datef.getText();
        String stat = statf.getText();

        
        if(cheq.equals("") || amnt.equals("") || date.equals("") || stat.equals("")){
            if(cheq.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter Cheque number!");}
            else if(amnt.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter Cash amount!");}
            else if(date.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter Date Issued!");}
            else if(stat.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter status of the bill!");}
            else{
                JOptionPane.showMessageDialog(this, "Please fill the fields properly!");}
        }
        else{
            try{
                Connection conn = dbcon.getConnection();

                String query = "INSERT INTO `iams`.`cash_ledger` (`account_no`, `amount`, `date_added`, `cheq_status`) VALUES('" + cheq + "','" + amount + "','" + date + "','Pending')";

                Statement stmt = conn.createStatement();
                int t = stmt.executeUpdate(query);
                if(t == 0){
                    JOptionPane.showMessageDialog(this, "Entry already exists");
                    } 
                else {
                    JOptionPane.showMessageDialog(this, "Entry successfully added");
                    }
                conn.close();
            }
            catch(SQLException e){
                e.printStackTrace();
            }
            catch (ClassNotFoundException e1) {
            e1.printStackTrace();
            }
        }
    }//GEN-LAST:event_addbillbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = dbcon.getConnection();
            String query5 = "SELECT * FROM `cash_ledger`";

            //Statement state = (Statement) conn.createStatement();
            PreparedStatement pst = conn.prepareStatement(query5);

            ResultSet res = pst.executeQuery();
            //ResultSetMetaData res = res1.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            //String columns[] = {"ID", "Username", "Email", "Name", "Employee_position"};
            //String data[][] = new String[12][5];

            //int i = 0;
            while(res.next()){               
                model.addRow(new Object[]{res.getInt("ID"), res.getString("account_no"), res.getString("amount"), res.getString("date_added"), res.getString("cheq_status")});

            }

            //DefaultTableModel model = new DefaultTableModel(data, columns);
            //model.addRow(data);

            conn.close();
            System.out.println("Connection Terminated");
            }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_viewbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame.dispose();
        login sign = new login();
        sign.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void accptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accptbtnActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = dbcon.getConnection();
            String query6 = "SELECT * FROM `accepted_bills`";

            //Statement state = (Statement) conn.createStatement();
            PreparedStatement pst = conn.prepareStatement(query6);

            ResultSet res = pst.executeQuery();
            //ResultSetMetaData res = res1.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            //String columns[] = {"ID", "Username", "Email", "Name", "Employee_position"};
            //String data[][] = new String[12][5];

            //int i = 0;
            while(res.next()){               
                model.addRow(new Object[]{res.getInt("ID"), res.getString("account_no"), res.getString("amount"), res.getString("date_added"), res.getString("cheq_status")});

            }

            //DefaultTableModel model = new DefaultTableModel(data, columns);
            //model.addRow(data);

            conn.close();
            System.out.println("Connection Terminated");
            }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_accptbtnActionPerformed

    private void dclnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dclnbtnActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = dbcon.getConnection();
            String query8 = "SELECT * FROM `rejected_bills`";

            //Statement state = (Statement) conn.createStatement();
            PreparedStatement pst = conn.prepareStatement(query8);

            ResultSet res = pst.executeQuery();
            //ResultSetMetaData res = res1.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            //String columns[] = {"ID", "Username", "Email", "Name", "Employee_position"};
            //String data[][] = new String[12][5];

            //int i = 0;
            while(res.next()){               
                model.addRow(new Object[]{res.getInt("ID"), res.getString("account_no"), res.getString("amount"), res.getString("date_added"), res.getString("cheq_status")});

            }

            //DefaultTableModel model = new DefaultTableModel(data, columns);
            //model.addRow(data);

            conn.close();
            System.out.println("Connection Terminated");
            }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_dclnbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new cashmanager();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accptbtn;
    private javax.swing.JButton addbillbtn;
    private javax.swing.JTextField amntf;
    private javax.swing.JTextField chqf;
    private javax.swing.JFormattedTextField datef;
    private javax.swing.JButton dclnbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField statf;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
    static cashmanager frame;
}
